### ISSUE TITLE
Clone issue 

### ISSUE THREAD

**Issue by chaitanya-online** [yuva19102003/2048-game-aws-beanstalk-dockerfile#1]
Hi While cloning into my local getting the below error  can you please check
![Screenshot_1](https://github.com/yuva19102003/2048-game-aws-beanstalk-dockerfile/assets/60810937/b63d3284-1a2e-4a7b-8046-b4b5b63b6f07)

**Comment by yuva19102003** [comment]
you're using a wrong link for cloning the repository, that link is for [ curl command ] only it will directly import the repository as a zip file only that link won't support for git command . for git clone use the http link from the github repository .

otherwise use this to clone the repository :
```bash
git clone https://github.com/yuva19102003/2048-game-aws-beanstalk-dockerfile.git
```

**Comment by chaitanya-online** [comment]
Thanks for info

**Comment by yuva19102003** [comment]
Have a nice day ✌🏻
